"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/field";
import type { SuggestedItem } from "@/lib/ai-validation";

export function AiSuggestions({ tripId, dayPlanId, hasPark, disabled, onApply }: { tripId: string; dayPlanId: string; hasPark: boolean; disabled: boolean; onApply: (items: SuggestedItem[]) => void }) {
  const [open, setOpen] = useState(false); const [preferences, setPreferences] = useState(""); const [items, setItems] = useState<SuggestedItem[]>([]); const [summary, setSummary] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function suggest() { setLoading(true); setError(null); setItems([]); try { const response = await fetch(`/api/trips/${tripId}/suggestions`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dayPlanId, preferences }) }); const result = await response.json() as { message?: string; summary?: string; items?: SuggestedItem[] }; if (!response.ok || !result.items) throw new Error(result.message ?? "Could not create suggestions."); setSummary(result.summary ?? ""); setItems(result.items); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not create suggestions."); } finally { setLoading(false); } }
  if (!open) return <Button type="button" variant="secondary" disabled={!hasPark || disabled} onClick={() => setOpen(true)} className="w-full">Suggest a day with AI</Button>;
  return <section className="space-y-3 rounded-control border border-gold/30 bg-sand/15 p-4"><div className="flex justify-between gap-2"><h4 className="font-semibold text-primary">AI day suggestions</h4><button type="button" onClick={() => setOpen(false)} className="text-sm text-muted">Close</button></div><Textarea value={preferences} onChange={(event) => setPreferences(event.target.value)} maxLength={1000} rows={3} placeholder="Optional preferences for this day. Your saved party profile is included automatically." /><Button type="button" disabled={loading} onClick={suggest}>{loading ? "Building ideas…" : "Generate suggestions"}</Button>{error && <p className="text-sm text-danger">{error}</p>}{items.length > 0 && <><p className="text-sm text-primary">{summary}</p><ol className="space-y-2">{items.map((item) => <li key={item.entityId} className="rounded-control border border-border bg-surface p-3 text-sm"><strong>{item.startTime} · {item.title}</strong><p className="mt-1 text-xs text-muted">{item.reason}</p></li>)}</ol><Button type="button" disabled={disabled} onClick={() => { onApply(items); setOpen(false); }}>Add all suggestions</Button></>}<p className="text-[11px] text-muted">AI suggestions can be inaccurate. Verify hours, reservations, and accessibility needs.</p></section>;
}
