import { format, parseISO } from "date-fns";
import Link from "next/link";
import { ParkMark } from "@/components/park-mark";
import { Badge } from "@/components/ui/badge";
import { buttonStyles } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { resolveDayTheme } from "@/lib/day-themes";
import type { ReservationSummary } from "./reservation-center";

type TodayItem = { id: string; title: string; entityType: string; timingType: string; timeOfDay: string | null; startTime: string | null; endTime: string | null; bookingStatus: string; confirmationNumber: string | null; notes: string | null };
type TodayDay = { id: string; date: string; parkName: string | null; secondaryParkName: string | null; notes: string | null; items: TodayItem[] };
type Moment = { id: string; title: string; category: string; time: string | null; timingLabel: string; status: string; confirmationNumber: string | null; location: string | null; notes: string | null; source: "reservation" | "plan" };

export function TodayView({ tripId, day, hotelName, reservations, companionCount, activeToday }: { tripId: string; day: TodayDay; hotelName: string | null; reservations: ReservationSummary[]; companionCount: number; activeToday: boolean }) {
  const theme = resolveDayTheme({ parkName: day.parkName, hotelName });
  const dayReservations = reservations.filter((item) => item.dayPlanId === day.id || item.date === day.date);
  const moments: Moment[] = [
    ...day.items.map((item) => ({ id: item.id, title: item.title, category: item.entityType, time: item.startTime, timingLabel: timingLabel(item), status: item.bookingStatus, confirmationNumber: item.confirmationNumber, location: null, notes: item.notes, source: "plan" as const })),
    ...dayReservations.map((item) => ({ id: item.id, title: item.title, category: item.category, time: item.startTime, timingLabel: item.startTime ? clock(item.startTime) : "Time to be set", status: item.status, confirmationNumber: item.confirmationNumber, location: item.location, notes: item.notes, source: "reservation" as const })),
  ].sort((a, b) => sortValue(a) - sortValue(b));
  const next = nextMoment(moments, activeToday);
  const confirmed = moments.filter((item) => item.confirmationNumber).length;

  return <div data-theme={theme.id} data-pattern={theme.pattern} className="day-theme overflow-hidden rounded-[1.75rem] border border-[rgb(var(--day-accent)/.24)] shadow-lift">
    <header className="day-theme__hero relative overflow-hidden border-b border-[rgb(var(--day-accent)/.2)] p-5 sm:p-7"><div className="absolute right-5 top-5 opacity-15 sm:right-8 sm:top-7" aria-hidden="true"><ParkMark theme={theme.id} className="size-28" /></div><div className="relative max-w-3xl"><p className="day-accent-text text-[10px] font-bold uppercase tracking-[0.22em]">{activeToday ? "Today at Walt Disney World" : "Today mode preview"}</p><h2 className="mt-2 text-3xl font-semibold text-primary sm:text-5xl">{greeting()}, adventure awaits.</h2><p className="mt-3 font-display text-lg text-muted">{format(parseISO(day.date), "EEEE, MMMM d")} · {day.parkName || (hotelName ? "A resort day" : "An open day")}{day.secondaryParkName ? ` · Hopper to ${day.secondaryParkName}` : ""}</p>{!activeToday && <p className="mt-3 max-w-xl text-sm leading-relaxed text-muted">This is how your in-park companion will feel. On the actual date, it will open on the current trip day and emphasize what is coming next.</p>}<div className="mt-5 flex flex-wrap gap-2"><Link href={`/trips/${tripId}?view=day&day=${day.id}#day-canvas`} className={buttonStyles({ size: "sm" })}>Edit this day</Link><Link href={`/trips/${tripId}?view=reservations`} className={buttonStyles({ variant: "secondary", size: "sm" })}>All reservations</Link></div></div></header>

    <div className="grid gap-5 bg-white/35 p-4 sm:p-6 lg:grid-cols-[minmax(0,1fr)_19rem]">
      <main className="min-w-0 space-y-4"><section aria-labelledby="next-up-title"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-gold">Up next</p>{next ? <Card className="mt-2 border-l-4 border-l-[rgb(var(--day-accent))] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="day-accent-text text-xs font-bold">{next.timingLabel}</p><h3 id="next-up-title" className="mt-1 font-display text-2xl font-semibold text-primary">{next.title}</h3><p className="mt-2 text-sm text-muted">{categoryLabel(next.category)}{next.location ? ` · ${next.location}` : ""}</p></div>{next.status !== "NONE" && <Badge tone={isConfirmed(next.status) ? "success" : "warning"}>{statusLabel(next.status)}</Badge>}</div>{next.confirmationNumber && <p className="mt-4 inline-flex rounded-full bg-parchment px-3 py-1.5 font-mono text-xs font-semibold text-primary">Confirmation {next.confirmationNumber}</p>}{next.notes && <p className="mt-3 text-sm leading-relaxed text-muted">{next.notes}</p>}</Card> : <Card className="mt-2 border-dashed p-5"><h3 id="next-up-title" className="font-display text-xl font-semibold text-primary">The day is yours</h3><p className="mt-2 text-sm text-muted">Nothing is scheduled yet. Add one anchor moment and leave room for discovery.</p></Card>}</section>

      <section aria-labelledby="today-schedule-title"><div className="flex items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-gold">Your day at a glance</p><h3 id="today-schedule-title" className="mt-1 text-2xl font-semibold text-primary">Today’s story</h3></div><Badge>{moments.length} moment{moments.length === 1 ? "" : "s"}</Badge></div>{moments.length ? <ol className="relative mt-4 space-y-3 before:absolute before:bottom-5 before:left-[1.18rem] before:top-5 before:w-px before:bg-[rgb(var(--day-accent)/.22)]">{moments.map((item) => <li key={`${item.source}-${item.id}`} className="relative grid grid-cols-[2.4rem_minmax(0,1fr)] gap-3"><span className="relative z-10 mt-4 grid size-9 place-items-center rounded-full border border-[rgb(var(--day-accent)/.22)] bg-white day-accent-text">{item.source === "reservation" ? "◇" : "•"}</span><Card className={`p-4 ${item.id === next?.id && item.source === next.source ? "ring-2 ring-[rgb(var(--day-accent)/.2)]" : ""}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="day-accent-text text-[10px] font-bold uppercase tracking-wider">{item.timingLabel}</p><h4 className="mt-1 font-semibold text-primary">{item.title}</h4><p className="mt-1 text-xs text-muted">{categoryLabel(item.category)}{item.location ? ` · ${item.location}` : ""}</p></div>{item.status !== "NONE" && <Badge tone={isConfirmed(item.status) ? "success" : "warning"}>{statusLabel(item.status)}</Badge>}</div></Card></li>)}</ol> : <Card className="mt-4 border-dashed p-5 text-center"><p className="font-display text-lg font-semibold text-primary">No plans yet</p><p className="mt-1 text-sm text-muted">Use the day planner to add attractions, meals, or a simple flexible idea.</p></Card>}</section></main>

      <aside className="space-y-3 lg:sticky lg:top-24 lg:self-start"><Card className="p-4"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-gold">Ready for the day</p><h3 className="mt-1 font-display text-xl font-semibold text-primary">Quick check</h3><ul className="mt-4 space-y-3 text-sm"><CheckRow done={Boolean(day.parkName || day.notes)} label={day.parkName ? "Park selected" : day.notes ? "Resort-day intention set" : "Choose today’s setting"} /><CheckRow done={moments.length > 0} label={moments.length ? `${moments.length} moments planned` : "Add an anchor moment"} /><CheckRow done={confirmed > 0} label={confirmed ? `${confirmed} confirmation${confirmed === 1 ? "" : "s"} handy` : "Store confirmation numbers"} /><CheckRow done={companionCount > 0} label={`${companionCount + 1} traveler${companionCount ? "s" : ""} in the party`} /></ul></Card>{hotelName && <Card className="p-4"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-muted">Home base</p><p className="mt-1 font-display text-lg font-semibold text-primary">{hotelName}</p></Card>}{day.notes && <Card className="p-4"><p className="text-[9px] font-bold uppercase tracking-[0.16em] text-muted">Day note</p><p className="mt-2 text-sm leading-relaxed text-muted">{day.notes}</p></Card>}</aside>
    </div>
  </div>;
}

function CheckRow({ done, label }: { done: boolean; label: string }) { return <li className="flex items-center gap-2.5"><span className={`grid size-5 shrink-0 place-items-center rounded-full text-[10px] font-bold ${done ? "bg-success text-white" : "border border-border bg-parchment text-muted"}`}>{done ? "✓" : "•"}</span><span className={done ? "text-primary" : "text-muted"}>{label}</span></li>; }
function sortValue(item: Moment) { if (item.time) return Number(item.time.replace(":", "")); if (/morning/i.test(item.timingLabel)) return 800; if (/afternoon/i.test(item.timingLabel)) return 1300; if (/evening/i.test(item.timingLabel)) return 1800; return 2359; }
function nextMoment(items: Moment[], active: boolean) { if (!active) return items[0] ?? null; const now = new Date(); const current = now.getHours() * 100 + now.getMinutes(); return items.find((item) => item.time && Number(item.time.replace(":", "")) >= current) ?? items.find((item) => !item.time) ?? items.at(-1) ?? null; }
function timingLabel(item: TodayItem) { if (item.timingType === "EXACT" && item.startTime) return clock(item.startTime); if (item.timingType === "TIME_OF_DAY" && item.timeOfDay) return item.timeOfDay.charAt(0) + item.timeOfDay.slice(1).toLowerCase(); return "Flexible"; }
function clock(value: string) { const [hour, minute] = value.split(":").map(Number); return new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit", timeZone: "UTC" }).format(new Date(Date.UTC(2020, 0, 1, hour, minute))); }
function greeting() { const hour = new Date().getHours(); return hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening"; }
function isConfirmed(value: string) { return value === "CONFIRMED" || value === "BOOKED"; }
function statusLabel(value: string) { return value === "CONFIRMED" || value === "BOOKED" ? "Confirmed" : value === "WISHLIST" ? "Wish list" : "Needs action"; }
function categoryLabel(value: string) { return ({ RESTAURANT: "Dining", ATTRACTION: "Attraction", SHOW: "Show", EXPERIENCE: "Experience", DINING: "Dining", HOTEL: "Hotel", FLIGHT: "Flight", TRANSPORT: "Transportation", TICKET: "Tickets", EVENT: "Special event", OTHER: "Plan" } as Record<string, string>)[value] ?? "Plan"; }
