"use client";

import { FormEvent, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { SyncEntitiesButton } from "@/components/sync-entities-button";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import type { PartyProfile } from "@/lib/trip-management-validation";
import { assignHotel, deleteTrip, updatePartyProfile, updateTrip, type MutationResult } from "./actions";

type Hotel = { id: string; name: string };
type TripValues = { id: string; name: string; startDate: string; endDate: string; budget: string; notes: string; hotelId: string | null; partyProfile: PartyProfile };
const fieldClass = "mt-1.5 w-full rounded-control border border-border bg-surface px-3.5 py-2.5 text-sm outline-none transition focus:border-gold focus:ring-4 focus:ring-gold/15";

export function TripSettings({ trip, hotels }: { trip: TripValues; hotels: Hotel[] }) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  function run(action: () => Promise<MutationResult>) { setError(null); setMessage(null); startTransition(async () => { try { const result = await action(); if (result.success) { setMessage(result.message ?? "Saved."); router.refresh(); } else setError(result.message); } catch { setError("That change could not be saved. Please try again."); } }); }
  function submitTrip(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => updateTrip({ tripId: trip.id, name: form.get("name"), startDate: form.get("startDate"), endDate: form.get("endDate"), budget: form.get("budget"), notes: form.get("notes") })); }
  function submitParty(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => updatePartyProfile({ tripId: trip.id, partySize: form.get("partySize"), ages: form.get("ages"), dietaryNotes: form.get("dietaryNotes"), accessibilityNotes: form.get("accessibilityNotes"), mustDos: form.get("mustDos"), avoidList: form.get("avoidList") })); }

  return <><Button type="button" variant="secondary" size="sm" onClick={() => setOpen(true)}>Settings</Button><Modal open={open} title="Trip, hotel & party settings" onClose={() => setOpen(false)}><div className="space-y-6">
    {(message || error) && <p role="status" className={`rounded-control p-3 text-sm ${error ? "bg-danger/5 text-danger" : "bg-success/5 text-success"}`}>{error ?? message}</p>}
    <form onSubmit={submitTrip} className="space-y-3"><h3 className="font-display text-lg font-semibold text-primary">Trip details</h3><label className="block text-sm font-semibold">Trip name<input name="name" required maxLength={100} defaultValue={trip.name} className={fieldClass} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Start date<input name="startDate" type="date" required defaultValue={trip.startDate} className={fieldClass} /></label><label className="text-sm font-semibold">End date<input name="endDate" type="date" required defaultValue={trip.endDate} className={fieldClass} /></label></div><p className="text-xs text-muted">Shortening a trip removes only empty days. Clear excluded days first.</p><label className="block text-sm font-semibold">Budget ($)<input name="budget" type="number" min="0" step="0.01" defaultValue={trip.budget} className={fieldClass} /></label><label className="block text-sm font-semibold">Trip notes<textarea name="notes" rows={2} maxLength={2000} defaultValue={trip.notes} className={fieldClass} /></label><Button disabled={pending} size="sm">Save trip details</Button></form>
    <section className="border-t border-border pt-5"><h3 className="font-display text-lg font-semibold text-primary">WDW hotel</h3><label className="mt-3 block text-sm font-semibold">Resort hotel<select value={trip.hotelId ?? ""} disabled={pending} onChange={(event) => run(() => assignHotel({ tripId: trip.id, hotelId: event.target.value || null }))} className={fieldClass}><option value="">No hotel selected</option>{hotels.map((hotel) => <option key={hotel.id} value={hotel.id}>{hotel.name}</option>)}</select></label>{hotels.length === 0 && <div className="mt-3 space-y-3"><p className="text-xs text-warning">No cached hotels yet. Refresh the WDW directory to add the resort catalog.</p><SyncEntitiesButton /></div>}</section>
    <form onSubmit={submitParty} className="space-y-3 border-t border-border pt-5"><div><h3 className="font-display text-lg font-semibold text-primary">Party profile</h3><p className="mt-1 text-xs text-muted">Included automatically in AI day suggestions.</p></div><label className="block text-sm font-semibold">Party size<input name="partySize" type="number" min="1" max="50" required defaultValue={trip.partyProfile.partySize} className={fieldClass} /></label><label className="block text-sm font-semibold">Ages or age bands<input name="ages" maxLength={300} defaultValue={trip.partyProfile.ages} className={fieldClass} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-semibold">Dietary notes<textarea name="dietaryNotes" rows={2} maxLength={1000} defaultValue={trip.partyProfile.dietaryNotes} className={fieldClass} /></label><label className="block text-sm font-semibold">Accessibility notes<textarea name="accessibilityNotes" rows={2} maxLength={1000} defaultValue={trip.partyProfile.accessibilityNotes} className={fieldClass} /></label><label className="block text-sm font-semibold">Must-dos<textarea name="mustDos" rows={2} maxLength={1000} defaultValue={trip.partyProfile.mustDos} className={fieldClass} /></label><label className="block text-sm font-semibold">Avoid list<textarea name="avoidList" rows={2} maxLength={1000} defaultValue={trip.partyProfile.avoidList} className={fieldClass} /></label></div><Button disabled={pending} size="sm">Save party profile</Button></form>
    <section className="border-t border-danger/15 pt-5"><h3 className="font-semibold text-danger">Delete trip</h3><p className="mt-1 text-xs text-muted">Permanently removes every planning day and item.</p><Button type="button" variant="danger" size="sm" className="mt-3" disabled={pending} onClick={() => { if (window.confirm(`Permanently delete “${trip.name}”? This cannot be undone.`)) startTransition(() => deleteTrip({ tripId: trip.id })); }}>Delete this trip</Button></section>
  </div></Modal></>;
}
