"use client";

import { FormEvent, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { SyncEntitiesButton } from "@/components/sync-entities-button";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import type { PartyProfile } from "@/lib/trip-management-validation";
import { assignHotel, deleteTrip, updatePartyProfile, updateTrip, type MutationResult } from "./actions";

type Hotel = { id: string; name: string };
type TripValues = { id: string; name: string; startDate: string; endDate: string; budget: string; notes: string; hotelId: string | null; customHotelName: string | null; partyProfile: PartyProfile };
type DirectoryStatus = { hotelCount: number; lastSynced: string | null };
const fieldClass = "mt-1.5 w-full rounded-control border border-border bg-surface px-3.5 py-2.5 text-sm outline-none transition focus:border-gold focus:ring-4 focus:ring-gold/15";

export function TripSettings({ trip, hotels, directoryStatus, triggerLabel = "Settings", triggerClassName }: { trip: TripValues; hotels: Hotel[]; directoryStatus: DirectoryStatus; triggerLabel?: string; triggerClassName?: string }) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [hotelChoice, setHotelChoice] = useState(trip.hotelId ?? (trip.customHotelName ? "__custom" : ""));
  function run(action: () => Promise<MutationResult>) { setError(null); setMessage(null); startTransition(async () => { try { const result = await action(); if (result.success) { setMessage(result.message ?? "Saved."); router.refresh(); } else setError(result.message); } catch { setError("That change could not be saved. Please try again."); } }); }
  function submitTrip(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => updateTrip({ tripId: trip.id, name: form.get("name"), startDate: form.get("startDate"), endDate: form.get("endDate"), budget: form.get("budget"), notes: form.get("notes") })); }
  function submitParty(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => updatePartyProfile({ tripId: trip.id, partySize: form.get("partySize"), ages: form.get("ages"), dietaryNotes: form.get("dietaryNotes"), accessibilityNotes: form.get("accessibilityNotes"), mustDos: form.get("mustDos"), avoidList: form.get("avoidList") })); }

  return <><Button type="button" variant="secondary" size="sm" className={triggerClassName} onClick={() => setOpen(true)}>{triggerLabel}</Button><Modal open={open} title="Trip settings" onClose={() => setOpen(false)}><div className="space-y-6">
    {(message || error) && <p role="status" className={`rounded-control p-3 text-sm ${error ? "bg-danger/5 text-danger" : "bg-success/5 text-success"}`}>{error ?? message}</p>}
    <form onSubmit={submitTrip} className="space-y-3"><h3 className="font-display text-lg font-semibold text-primary">Trip details</h3><label className="block text-sm font-semibold">Trip name<input name="name" required maxLength={100} defaultValue={trip.name} className={fieldClass} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Start date<input name="startDate" type="date" required defaultValue={trip.startDate} className={fieldClass} /></label><label className="text-sm font-semibold">End date<input name="endDate" type="date" required defaultValue={trip.endDate} className={fieldClass} /></label></div><p className="text-xs text-muted">Shortening a trip removes only empty days. Clear excluded days first.</p><label className="block text-sm font-semibold">Budget ($)<input name="budget" type="number" min="0" step="0.01" defaultValue={trip.budget} className={fieldClass} /></label><label className="block text-sm font-semibold">Trip notes<textarea name="notes" rows={2} maxLength={2000} defaultValue={trip.notes} className={fieldClass} /></label><Button disabled={pending} size="sm">Save trip details</Button></form>
    <section className="space-y-3 border-t border-border pt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-display text-lg font-semibold text-primary">Your hotel</h3><p className="mt-1 text-xs text-muted">Choose a Disney resort or enter any off-property hotel.</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${hotels.length ? "bg-success/10 text-success" : "bg-warning/10 text-warning"}`}>{hotels.length ? `${hotels.length} resorts ready` : "Catalog not loaded"}</span></div><label className="block text-sm font-semibold">Hotel or resort<select value={hotelChoice} disabled={pending} onChange={(event) => { const value = event.target.value; setHotelChoice(value); if (value !== "__custom") run(() => assignHotel({ tripId: trip.id, hotelId: value || null, customHotelName: null })); }} className={fieldClass}><option value="">No hotel selected</option>{hotels.map((hotel) => <option key={hotel.id} value={hotel.id}>{hotel.name}</option>)}<option value="__custom">My hotel isn’t listed…</option></select></label>{hotelChoice === "__custom" && <form className="rounded-control border border-gold/25 bg-sand/10 p-3" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => assignHotel({ tripId: trip.id, hotelId: null, customHotelName: form.get("customHotelName") })); }}><label className="block text-sm font-semibold">Hotel name<input name="customHotelName" required maxLength={120} defaultValue={trip.customHotelName ?? ""} placeholder="For example, Swan Reserve" className={fieldClass} /></label><Button size="sm" className="mt-3" disabled={pending}>Save hotel</Button></form>}<div className="rounded-control border border-border bg-parchment/60 p-3"><SyncEntitiesButton compact hotelCount={directoryStatus.hotelCount} lastSynced={directoryStatus.lastSynced} /><p className="mt-2 text-[11px] leading-relaxed text-muted">Refreshing is optional. Manual hotel entry always remains available.</p></div></section>
    <form onSubmit={submitParty} className="space-y-3 border-t border-border pt-5"><div><h3 className="font-display text-lg font-semibold text-primary">Travelers</h3><p className="mt-1 text-xs text-muted">Tell us who is coming. Everything beyond party size is optional.</p></div><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm font-semibold">How many people?<input name="partySize" type="number" min="1" max="50" required defaultValue={trip.partyProfile.partySize} className={fieldClass} /></label><label className="block text-sm font-semibold">Ages, optional<input name="ages" maxLength={300} defaultValue={trip.partyProfile.ages} placeholder="Two adults, ages 8 and 11" className={fieldClass} /></label></div><details className="group rounded-control border border-border bg-parchment/45 p-3"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-sm font-semibold text-primary"><span>Add food, accessibility, or preference notes</span><span className="text-muted transition group-open:rotate-180" aria-hidden="true">⌄</span></summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="block text-sm font-semibold">Food needs<textarea name="dietaryNotes" rows={2} maxLength={1000} defaultValue={trip.partyProfile.dietaryNotes} className={fieldClass} /></label><label className="block text-sm font-semibold">Accessibility needs<textarea name="accessibilityNotes" rows={2} maxLength={1000} defaultValue={trip.partyProfile.accessibilityNotes} className={fieldClass} /></label><label className="block text-sm font-semibold">Things we love<textarea name="mustDos" rows={2} maxLength={1000} defaultValue={trip.partyProfile.mustDos} className={fieldClass} /></label><label className="block text-sm font-semibold">Things to avoid<textarea name="avoidList" rows={2} maxLength={1000} defaultValue={trip.partyProfile.avoidList} className={fieldClass} /></label></div></details><Button disabled={pending} size="sm">Save travelers</Button></form>
    <details className="group border-t border-border pt-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 text-sm font-semibold text-muted"><span>More settings</span><span className="transition group-open:rotate-180" aria-hidden="true">⌄</span></summary><div className="mt-4 rounded-control border border-danger/15 bg-danger/5 p-4"><h3 className="font-semibold text-danger">Delete trip</h3><p className="mt-1 text-xs text-muted">Permanently removes every planning day and item.</p><Button type="button" variant="danger" size="sm" className="mt-3" disabled={pending} onClick={() => { if (window.confirm(`Permanently delete “${trip.name}”? This cannot be undone.`)) startTransition(() => deleteTrip({ tripId: trip.id })); }}>Delete this trip</Button></div></details>
  </div></Modal></>;
}
