ALTER TABLE "DayPlanItem" ADD COLUMN IF NOT EXISTS "timingType" TEXT NOT NULL DEFAULT 'FLEXIBLE';
ALTER TABLE "DayPlanItem" ADD COLUMN IF NOT EXISTS "timeOfDay" TEXT;

UPDATE "DayPlanItem"
SET "timingType" = 'EXACT'
WHERE "startTime" IS NOT NULL;
